package edu.iub.pubmed.dto;

// Generated Mar 21, 2014 5:53:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AuthorReference generated by hbm2java
 */
@Entity
@Table(name = "author_reference", catalog = "pubmedcentral")
public class AuthorReference implements java.io.Serializable {

	private AuthorReferenceId id;
	private String role;
	private String comments;

	public AuthorReference() {
	}

	public AuthorReference(AuthorReferenceId id) {
		this.id = id;
	}

	public AuthorReference(AuthorReferenceId id, String role, String comments) {
		this.id = id;
		this.role = role;
		this.comments = comments;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "id", column = @Column(name = "id", nullable = false)),
			@AttributeOverride(name = "pubmedId", column = @Column(name = "pubmed_id", nullable = false, length = 45)),
			@AttributeOverride(name = "authorId", column = @Column(name = "author_id", nullable = false)) })
	public AuthorReferenceId getId() {
		return this.id;
	}

	public void setId(AuthorReferenceId id) {
		this.id = id;
	}

	@Column(name = "role", length = 45)
	public String getRole() {
		return this.role;
	}

	public void setRole(String role) {
		this.role = role;
	}

	@Column(name = "comments", length = 100)
	public String getComments() {
		return this.comments;
	}

	public void setComments(String comments) {
		this.comments = comments;
	}

}
