package edu.iub.pubmed.dto;

// Generated Mar 19, 2014 7:17:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * AuthorReferenceId generated by hbm2java
 */
@Embeddable
public class AuthorReferenceId implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	private int id;
	private String pubmedId;
	private int authorId;

	public AuthorReferenceId() {
	}

	public AuthorReferenceId(int id, String pubmedId, int authorId) {
		this.id = id;
		this.pubmedId = pubmedId;
		this.authorId = authorId;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "pubmed_id", nullable = false, length = 45)
	public String getPubmedId() {
		return this.pubmedId;
	}

	public void setPubmedId(String pubmedId) {
		this.pubmedId = pubmedId;
	}

	@Column(name = "author_id", nullable = false)
	public int getAuthorId() {
		return this.authorId;
	}

	public void setAuthorId(int authorId) {
		this.authorId = authorId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AuthorReferenceId))
			return false;
		AuthorReferenceId castOther = (AuthorReferenceId) other;

		return (this.getId() == castOther.getId())
				&& ((this.getPubmedId() == castOther.getPubmedId()) || (this
						.getPubmedId() != null
						&& castOther.getPubmedId() != null && this
						.getPubmedId().equals(castOther.getPubmedId())))
				&& (this.getAuthorId() == castOther.getAuthorId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getId();
		result = 37 * result
				+ (getPubmedId() == null ? 0 : this.getPubmedId().hashCode());
		result = 37 * result + this.getAuthorId();
		return result;
	}

}
