package edu.iub.pubmed.dto;

// Generated Mar 21, 2014 5:53:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CategoryReferenceId generated by hbm2java
 */
@Embeddable
public class CategoryReferenceId implements java.io.Serializable {

	private String pubmedId;
	private int categoryId;

	public CategoryReferenceId() {
	}

	public CategoryReferenceId(String pubmedId, int categoryId) {
		this.pubmedId = pubmedId;
		this.categoryId = categoryId;
	}

	@Column(name = "pubmed_id", nullable = false, length = 45)
	public String getPubmedId() {
		return this.pubmedId;
	}

	public void setPubmedId(String pubmedId) {
		this.pubmedId = pubmedId;
	}

	@Column(name = "category_id", nullable = false)
	public int getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(int categoryId) {
		this.categoryId = categoryId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CategoryReferenceId))
			return false;
		CategoryReferenceId castOther = (CategoryReferenceId) other;

		return ((this.getPubmedId() == castOther.getPubmedId()) || (this
				.getPubmedId() != null && castOther.getPubmedId() != null && this
				.getPubmedId().equals(castOther.getPubmedId())))
				&& (this.getCategoryId() == castOther.getCategoryId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPubmedId() == null ? 0 : this.getPubmedId().hashCode());
		result = 37 * result + this.getCategoryId();
		return result;
	}

}
