package edu.iub.pubmed.dto;

// Generated Mar 21, 2014 5:53:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CategoryReference generated by hbm2java
 */
@Entity
@Table(name = "category_reference", catalog = "pubmedcentral")
public class CategoryReference implements java.io.Serializable {

	private CategoryReferenceId id;
	private String dummyCol;

	public CategoryReference() {
	}

	public CategoryReference(CategoryReferenceId id) {
		this.id = id;
	}

	public CategoryReference(CategoryReferenceId id, String dummyCol) {
		this.id = id;
		this.dummyCol = dummyCol;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pubmedId", column = @Column(name = "pubmed_id", nullable = false, length = 45)),
			@AttributeOverride(name = "categoryId", column = @Column(name = "category_id", nullable = false)) })
	public CategoryReferenceId getId() {
		return this.id;
	}

	public void setId(CategoryReferenceId id) {
		this.id = id;
	}

	@Column(name = "dummy_col", length = 10)
	public String getDummyCol() {
		return this.dummyCol;
	}

	public void setDummyCol(String dummyCol) {
		this.dummyCol = dummyCol;
	}

}
