package edu.iub.pubmed.dto;

// Generated Mar 21, 2014 5:53:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", catalog = "pubmedcentral")
public class Category implements java.io.Serializable {

	private Integer categoryId;
	private int parentCategoryId;
	private String subject;
	private String seriesTitle;
	private String seriesText;

	public Category() {
	}

	public Category(int parentCategoryId, String subject) {
		this.parentCategoryId = parentCategoryId;
		this.subject = subject;
	}

	public Category(int parentCategoryId, String subject, String seriesTitle,
			String seriesText) {
		this.parentCategoryId = parentCategoryId;
		this.subject = subject;
		this.seriesTitle = seriesTitle;
		this.seriesText = seriesText;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "category_id", unique = true, nullable = false)
	public Integer getCategoryId() {
		return this.categoryId;
	}

	public void setCategoryId(Integer categoryId) {
		this.categoryId = categoryId;
	}

	@Column(name = "parent_category_id", nullable = false)
	public int getParentCategoryId() {
		return this.parentCategoryId;
	}

	public void setParentCategoryId(int parentCategoryId) {
		this.parentCategoryId = parentCategoryId;
	}

	@Column(name = "subject", nullable = false, length = 45)
	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

	@Column(name = "series_title", length = 45)
	public String getSeriesTitle() {
		return this.seriesTitle;
	}

	public void setSeriesTitle(String seriesTitle) {
		this.seriesTitle = seriesTitle;
	}

	@Column(name = "series_text", length = 45)
	public String getSeriesText() {
		return this.seriesText;
	}

	public void setSeriesText(String seriesText) {
		this.seriesText = seriesText;
	}

}
