package edu.iub.pubmed.dto;

// Generated Mar 21, 2014 5:53:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * CitationReference generated by hbm2java
 */
@Entity
@Table(name = "citation_reference", catalog = "pubmedcentral")
public class CitationReference implements java.io.Serializable {

	private CitationReferenceId id;
	private String leftText;
	private String rightText;

	public CitationReference() {
	}

	public CitationReference(CitationReferenceId id) {
		this.id = id;
	}

	public CitationReference(CitationReferenceId id, String leftText,
			String rightText) {
		this.id = id;
		this.leftText = leftText;
		this.rightText = rightText;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pubmedId", column = @Column(name = "pubmed_id", nullable = false, length = 45)),
			@AttributeOverride(name = "citationId", column = @Column(name = "citation_id", nullable = false)) })
	public CitationReferenceId getId() {
		return this.id;
	}

	public void setId(CitationReferenceId id) {
		this.id = id;
	}

	@Column(name = "left_text", length = 65535)
	public String getLeftText() {
		return this.leftText;
	}

	public void setLeftText(String leftText) {
		this.leftText = leftText;
	}

	@Column(name = "right_text", length = 65535)
	public String getRightText() {
		return this.rightText;
	}

	public void setRightText(String rightText) {
		this.rightText = rightText;
	}

}
