package edu.iub.pubmed.dto;

// Generated Mar 21, 2014 5:53:07 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Citation generated by hbm2java
 */
@Entity
@Table(name = "citation", catalog = "pubmedcentral")
public class Citation implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer citationId;
	private String publicationType;
	private String publicationFormat;
	private String publisherType;
	private String source;
	private String authors;
	private String articleTitle;
	private String volume;
	private String issue;
	private String name;
	private Date date;

	public Citation() {
	}

	public Citation(String publicationType, String publicationFormat,
			String publisherType, String source, String authors,
			String articleTitle, String volume, String issue, String name,
			Date date) {
		this.publicationType = publicationType;
		this.publicationFormat = publicationFormat;
		this.publisherType = publisherType;
		this.source = source;
		this.authors = authors;
		this.articleTitle = articleTitle;
		this.volume = volume;
		this.issue = issue;
		this.name = name;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "citation_id", unique = true, nullable = false)
	public Integer getCitationId() {
		return this.citationId;
	}

	public void setCitationId(Integer citationId) {
		this.citationId = citationId;
	}

	@Column(name = "publication_type", length = 45)
	public String getPublicationType() {
		return this.publicationType;
	}

	public void setPublicationType(String publicationType) {
		this.publicationType = publicationType;
	}

	@Column(name = "publication_format", length = 45)
	public String getPublicationFormat() {
		return this.publicationFormat;
	}

	public void setPublicationFormat(String publicationFormat) {
		this.publicationFormat = publicationFormat;
	}

	@Column(name = "publisher_type", length = 45)
	public String getPublisherType() {
		return this.publisherType;
	}

	public void setPublisherType(String publisherType) {
		this.publisherType = publisherType;
	}

	@Column(name = "source", length = 250)
	public String getSource() {
		return this.source;
	}

	public void setSource(String source) {
		this.source = source;
	}

	@Column(name = "authors", length = 256)
	public String getAuthors() {
		return this.authors;
	}

	public void setAuthors(String authors) {
		this.authors = authors;
	}

	@Column(name = "article_title", length = 1000)
	public String getArticleTitle() {
		return this.articleTitle;
	}

	public void setArticleTitle(String articleTitle) {
		this.articleTitle = articleTitle;
	}

	@Column(name = "volume", length = 45)
	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	@Column(name = "issue", length = 45)
	public String getIssue() {
		return this.issue;
	}

	public void setIssue(String issue) {
		this.issue = issue;
	}

	@Column(name = "name", length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
