package edu.iub.pubmed.dto;

// Generated Mar 21, 2014 5:53:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * CitationReferenceId generated by hbm2java
 */
@Embeddable
public class CitationReferenceId implements java.io.Serializable {

	private String pubmedId;
	private int citationId;

	public CitationReferenceId() {
	}

	public CitationReferenceId(String pubmedId, int citationId) {
		this.pubmedId = pubmedId;
		this.citationId = citationId;
	}

	@Column(name = "pubmed_id", nullable = false, length = 45)
	public String getPubmedId() {
		return this.pubmedId;
	}

	public void setPubmedId(String pubmedId) {
		this.pubmedId = pubmedId;
	}

	@Column(name = "citation_id", nullable = false)
	public int getCitationId() {
		return this.citationId;
	}

	public void setCitationId(int citationId) {
		this.citationId = citationId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CitationReferenceId))
			return false;
		CitationReferenceId castOther = (CitationReferenceId) other;

		return ((this.getPubmedId() == castOther.getPubmedId()) || (this
				.getPubmedId() != null && castOther.getPubmedId() != null && this
				.getPubmedId().equals(castOther.getPubmedId())))
				&& (this.getCitationId() == castOther.getCitationId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getPubmedId() == null ? 0 : this.getPubmedId().hashCode());
		result = 37 * result + this.getCitationId();
		return result;
	}

}
