package edu.iub.pubmed.dto;

// Generated Mar 19, 2014 7:17:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * JournalMetadata generated by hbm2java
 */
@Entity
@Table(name = "journal_Metadata", catalog = "pubmedcentral")
public class JournalMetadata implements java.io.Serializable {

	private Integer id;
	private String journalId;
	private String journalTitleGroup;
	private String issn;
	private String isbn;
	private String publisher;
	private String notes;
	private String customMetaGroup;

	public JournalMetadata() {
	}

	public JournalMetadata(String journalId, String journalTitleGroup,
			String issn, String isbn) {
		this.journalId = journalId;
		this.journalTitleGroup = journalTitleGroup;
		this.issn = issn;
		this.isbn = isbn;
	}

	public JournalMetadata(String journalId, String journalTitleGroup,
			String issn, String isbn, String publisher, String notes,
			String customMetaGroup) {
		this.journalId = journalId;
		this.journalTitleGroup = journalTitleGroup;
		this.issn = issn;
		this.isbn = isbn;
		this.publisher = publisher;
		this.notes = notes;
		this.customMetaGroup = customMetaGroup;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "journal_id", nullable = false, length = 45)
	public String getJournalId() {
		return this.journalId;
	}

	public void setJournalId(String journalId) {
		this.journalId = journalId;
	}

	@Column(name = "journal_title_group", nullable = false, length = 45)
	public String getJournalTitleGroup() {
		return this.journalTitleGroup;
	}

	public void setJournalTitleGroup(String journalTitleGroup) {
		this.journalTitleGroup = journalTitleGroup;
	}

	@Column(name = "issn", nullable = false, length = 45)
	public String getIssn() {
		return this.issn;
	}

	public void setIssn(String issn) {
		this.issn = issn;
	}

	@Column(name = "isbn", nullable = false, length = 45)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "publisher", length = 45)
	public String getPublisher() {
		return this.publisher;
	}

	public void setPublisher(String publisher) {
		this.publisher = publisher;
	}

	@Column(name = "notes", length = 45)
	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

	@Column(name = "custom_meta_group", length = 45)
	public String getCustomMetaGroup() {
		return this.customMetaGroup;
	}

	public void setCustomMetaGroup(String customMetaGroup) {
		this.customMetaGroup = customMetaGroup;
	}

}
