package edu.iub.pubmed.dto;

// Generated Mar 21, 2014 5:53:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Keyword generated by hbm2java
 */
@Entity
@Table(name = "keyword", catalog = "pubmedcentral")
public class Keyword implements java.io.Serializable {
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	private Integer keywordId;
	private String kwdGroupType;
	private String compoundKwdPartContentType;
	private String keywordText;

	public Keyword() {
	}

	public Keyword(String kwdGroupType, String compoundKwdPartContentType,
			String keywordText) {
		this.kwdGroupType = kwdGroupType;
		this.compoundKwdPartContentType = compoundKwdPartContentType;
		this.keywordText = keywordText;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "keyword_id", unique = true, nullable = false)
	public Integer getKeywordId() {
		return this.keywordId;
	}

	public void setKeywordId(Integer keywordId) {
		this.keywordId = keywordId;
	}

	@Column(name = "kwd_group_type", length = 45)
	public String getKwdGroupType() {
		return this.kwdGroupType;
	}

	public void setKwdGroupType(String kwdGroupType) {
		this.kwdGroupType = kwdGroupType;
	}

	@Column(name = "compound_kwd_part_content_type", length = 45)
	public String getCompoundKwdPartContentType() {
		return this.compoundKwdPartContentType;
	}

	public void setCompoundKwdPartContentType(String compoundKwdPartContentType) {
		this.compoundKwdPartContentType = compoundKwdPartContentType;
	}

	@Column(name = "keyword_text", length = 45)
	public String getKeywordText() {
		return this.keywordText;
	}

	public void setKeywordText(String keywordText) {
		this.keywordText = keywordText;
	}

}
