package edu.iub.pubmed.dto;

// Generated Mar 21, 2014 5:53:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * KeywordReference generated by hbm2java
 */
@Entity
@Table(name = "keyword_reference", catalog = "pubmedcentral")
public class KeywordReference implements java.io.Serializable {

	private KeywordReferenceId id;
	private String dummyCol;

	public KeywordReference() {
	}

	public KeywordReference(KeywordReferenceId id) {
		this.id = id;
	}

	public KeywordReference(KeywordReferenceId id, String dummyCol) {
		this.id = id;
		this.dummyCol = dummyCol;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pubmedId", column = @Column(name = "pubmed_id", nullable = false, length = 45)),
			@AttributeOverride(name = "keywordGroupId", column = @Column(name = "keyword_group_id", nullable = false)) })
	public KeywordReferenceId getId() {
		return this.id;
	}

	public void setId(KeywordReferenceId id) {
		this.id = id;
	}

	@Column(name = "dummy_col", length = 45)
	public String getDummyCol() {
		return this.dummyCol;
	}

	public void setDummyCol(String dummyCol) {
		this.dummyCol = dummyCol;
	}

}
