package edu.iub.pubmed.dto;

// Generated Mar 21, 2014 5:53:07 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * PubmedReference generated by hbm2java
 */
@Entity
@Table(name = "pubmed_reference", catalog = "pubmedcentral")
public class PubmedReference implements java.io.Serializable {

	private PubmedReferenceId id;
	private String leftText;
	private String rightText;

	public PubmedReference() {
	}

	public PubmedReference(PubmedReferenceId id) {
		this.id = id;
	}

	public PubmedReference(PubmedReferenceId id, String leftText,
			String rightText) {
		this.id = id;
		this.leftText = leftText;
		this.rightText = rightText;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "pubmedId", column = @Column(name = "pubmed_id", nullable = false, length = 45)),
			@AttributeOverride(name = "citedPubmedId", column = @Column(name = "cited_pubmed_id", nullable = false, length = 45)) })
	public PubmedReferenceId getId() {
		return this.id;
	}

	public void setId(PubmedReferenceId id) {
		this.id = id;
	}

	@Column(name = "left_text", length = 65535)
	public String getLeftText() {
		return this.leftText;
	}

	public void setLeftText(String leftText) {
		this.leftText = leftText;
	}

	@Column(name = "right_text", length = 65535)
	public String getRightText() {
		return this.rightText;
	}

	public void setRightText(String rightText) {
		this.rightText = rightText;
	}

}
