package edu.iub.pubmed.dto;

// Generated Mar 19, 2014 7:17:36 PM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * TypePubIdentifier generated by hbm2java
 */
@Entity
@Table(name = "type_pub_identifier", catalog = "pubmedcentral")
public class TypePubIdentifier implements java.io.Serializable {

	private int id;
	private String type;

	public TypePubIdentifier() {
	}

	public TypePubIdentifier(int id) {
		this.id = id;
	}

	public TypePubIdentifier(int id, String type) {
		this.id = id;
		this.type = type;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "type", length = 45)
	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

}
