package edu.iub.pubmed.dto;

// Generated Mar 19, 2014 7:17:36 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Volume generated by hbm2java
 */
@Entity
@Table(name = "volume", catalog = "pubmedcentral")
public class Volume implements java.io.Serializable {

	private String volumeId;
	private String volume;
	private String issue;
	private String issueId;
	private String issueTitle;
	private String issueSponsor;
	private Integer issuePart;
	private String isbn;
	private Set<Article> articles = new HashSet<Article>(0);

	public Volume() {
	}

	public Volume(String volumeId) {
		this.volumeId = volumeId;
	}

	public Volume(String volumeId, String volume, String issue, String issueId,
			String issueTitle, String issueSponsor, Integer issuePart,
			String isbn, Set<Article> articles) {
		this.volumeId = volumeId;
		this.volume = volume;
		this.issue = issue;
		this.issueId = issueId;
		this.issueTitle = issueTitle;
		this.issueSponsor = issueSponsor;
		this.issuePart = issuePart;
		this.isbn = isbn;
		this.articles = articles;
	}

	@Id
	@Column(name = "volume_id", unique = true, nullable = false, length = 45)
	public String getVolumeId() {
		return this.volumeId;
	}

	public void setVolumeId(String volumeId) {
		this.volumeId = volumeId;
	}

	@Column(name = "volume", length = 45)
	public String getVolume() {
		return this.volume;
	}

	public void setVolume(String volume) {
		this.volume = volume;
	}

	@Column(name = "issue", length = 45)
	public String getIssue() {
		return this.issue;
	}

	public void setIssue(String issue) {
		this.issue = issue;
	}

	@Column(name = "issue_id", length = 45)
	public String getIssueId() {
		return this.issueId;
	}

	public void setIssueId(String issueId) {
		this.issueId = issueId;
	}

	@Column(name = "issue_title", length = 100)
	public String getIssueTitle() {
		return this.issueTitle;
	}

	public void setIssueTitle(String issueTitle) {
		this.issueTitle = issueTitle;
	}

	@Column(name = "issue_sponsor", length = 45)
	public String getIssueSponsor() {
		return this.issueSponsor;
	}

	public void setIssueSponsor(String issueSponsor) {
		this.issueSponsor = issueSponsor;
	}

	@Column(name = "issue_part")
	public Integer getIssuePart() {
		return this.issuePart;
	}

	public void setIssuePart(Integer issuePart) {
		this.issuePart = issuePart;
	}

	@Column(name = "isbn", length = 45)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "volume")
	public Set<Article> getArticles() {
		return this.articles;
	}

	public void setArticles(Set<Article> articles) {
		this.articles = articles;
	}

}
